//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demka
{
    using System;
    using System.Collections.Generic;
    
    public partial class tkani
    {
        public long artikul_tkani { get; set; }
        public string naimenovanie { get; set; }
        public long risunok { get; set; }
        public Nullable<int> procent_sostav { get; set; }
        public double shirina { get; set; }
        public int dlina { get; set; }
        public int cena { get; set; }
    }
}
